### PR TITLE
New addroute!() that takes GPS coordinates in LLA format and plots them.

### PR DESCRIPTION
**Pull request by michael-prange**

### CODE REVIEW

**Comment by pszufe** [comment]
This just Great!
Could you however add 2 lines to src/runtests.jl similar to the lines 23 and 29 that contain a standard call to your method. In this way we will be sure it will not be broken by a future update. Thank you!

**Comment by michael-prange** [comment]
Will do. I’ve never done a PR before, so I hope I did it right.

**Comment by pszufe** [comment]
You have made a new pull request while you should have updated this one instead. 
When you click on the status of the other PR you will see that it is marked with red because the build has failed. The build has failed because now function `add_route!` and its tests are in two separate projects.

Maybe try to correct it (update this PR and I will close and remove the other), OK? However if you get stuck (working with git is not any easy!) let me know and I will sort it out :-)

**Comment by michael-prange** [comment]
I’m new to all this github stuff. Thank you for your patience. I will try to sort it out.

**Comment by michael-prange** [comment]
I think I've added the tests to this PR.

**Comment by pszufe** [comment]
Great!

**Pull request merged**
